### ISSUE TITLE
Add pages to manage challenges

### ISSUE THREAD

**Issue by plinck** [plinck/TeamATC#148]
**Is your feature request related to a problem? Please describe.**
Right now, there is just one challenge and it is kind of hardcoded into the environment.   It needs to be setup so users or admins can create challenges and invite people to join so multiple challenges can be going on at one.  How / where actives are store may need to be revisited but not sure.  At this point all activities are under a challenge and there really has never been any intent on being a repository for ALL actives - i.e. if some is in multiple challenges - they only see their activities for that challenge.  It makes sense since the vision of challenges was to be in one a year, for at least one at a time and clearly not multiple at the same time.

**Describe the solution you'd like**
I want to at least be able to create challenges on their and have athletes can create teams in those challenges and compete on anything they want.

**Describe alternatives you've considered**
 I am though a to about it but don't want it too complicated - it is not meant to compete with strava, training peaks etc but just for challenges.  But I still want to make it a bit more flexible.

The other good idea is having a user just enter their actives and have all those activities be under their user ID vs under the challenge.  That would allow their activities to apply to any challenge that they are in for that time period.  There are other big issues with this with regard to tracking a single challenge which was still the original MVP.  Since in this case, you would have to go through a list of participants in a challenge and go get all their activities.  That would be MUCH MUCH slower and is kind of the basis for all of it.

Strava does it like this.  Uses just have their activities.  They can join 0..N challenges and whatever they do in the time period of any challenge gets applied to it.

**Additional context**

**Comment by nanderson815** [comment]
I agree with your assessment. In order for this to work, we need to restructure our DB tying the activities to a user, rather than a challenge. (I am thinking this will be similar to a chat app, where messages - i.e. activities - are stored as an array of UIDs linked to the user. The activity data itself could be stored in its own array, and have a field for the user it relates to.

I will begin creating dummy front end pages/cards, and we can connect them to firestore once we decide on a structure.

**Comment by plinck** [comment]
Yes, in this case the activities should e stored in a sub collection under the user's document.  I am a tad worried about performance.A user will have a lo fo activities and activities do really belong to a user and can be there forever.  Then those activities can be part of a challenge if the user is part of the challenge AND the data of the activity is in the date range of the challenge.

One issue is performance.   Since in this case to get all activities for a challenge (a primary listener in the app), you would have to gather all the users in the challenge and loop through each of them selecting all activities within the date range of the challenge.

This is a much more flexible way to do it but wonder how fast it will be.  I will do some tests of that.

**Comment by plinck** [comment]
Getting realtime updates might be tricky but we really need the listener so that we don't have to refetch things over and over.  The listener would need to be able to detect when any activity in a challenge is added, changed, deleted.  Activities are indirectly tied to challenge (i.e. user is in the challenge and date is within challenge timeframe) go capturing this will need to be figured out.  It would be quite easy in SQL but a bit trickier in Firestore.  

Sort of thinking out loud ...

**Comment by plinck** [comment]
I went through a sample query for above and its hairy , slow and inefficient.  Thinking out loud again, maybe each time an activity is added, we can mark which challenge it applies to based on user, and date.  This could get out of sync but could have jobs running to fix.  In this case, any activity would only go to a challenge if it was entered after a se signed up for that challenge which may be OK in some cases.  So far I don't like many of these ideas.

Given that getting acvitiies for a specific challenge is the main use case, leaving them all under there for now may take the most sense.  They are already tied to a user so to get all for a user wee would have to go through all challenges.  Also, there are changes for duplicates if someone is participating in more than one challenge

**Comment by plinck** [comment]
I think we will have to leave it where it is for now. A bit of analysis paralysis.  But I am not happy the way it is but that is for another dat for now.  Want to move to firebase functions before switching as additional functions (like listCollections) becomes available that clients cant do nd I prefer not to do with standard node

**Comment by plinck** [comment]
I added CRUD for challenge and added date range.  

We need to always display the challenge a user is in and make sure teams, activities. etc are used for that challenge.  

on startup, the user should select which challenge they are in or it should automatically be selected for them based ont he current date - i.e. there may only be one that s active.  The user should be in that challenge until they change challenges - even if they logout and log back on.

**Comment by plinck** [comment]
Good for now
