### ISSUE TITLE
Fix Activity Data to include time.

### ISSUE THREAD

**Issue by nanderson815** [plinck/TeamATC#149]
**Describe the bug**
Date/Time field in the activity data only shows the date, time is 00:00:00. This is causing bugs in presenting data, especially in the bubble chart. Because the x values are the same, hovering the chart will show multiple bubbles instead of the nearest bubble.
**To Reproduce**
Hover anywhere on the bubble chart.
**Expected behavior**
Nearest single bubble should be shown.

**Screenshots**

**Additional context**

**Comment by plinck** [comment]
Thanks for the update on this.  Unfortunately, for the challenge, we only capture the date and not the time of the workout.  If they upload fit file we would get the exact time of the workout but folks just don't want to enter date and time.  I think I should give the ability to enter time in workout add but it still might not be used.  All data to this point is only date.

**Comment by plinck** [comment]
Added
