### ISSUE TITLE
When user isn't on a team, dashboard does not show ANYTHING

### ISSUE THREAD

**Issue by plinck** [plinck/TeamATC#162]
**Describe the bug**
If you are not on a team, the dashboard shows nothing. Not blank components - just nothing.  It should show but with non-team info.

**To Reproduce**
ave a user join a new challenge which will delete the team they are on since teams are part of a challenge.  Then, go to dashboard and see that its blank.  There may be errors in the debugger.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by plinck** [comment]
At a minimum, it should tell the user to join a team first.  But it should show the stuff that is in that challenge without showing your team or your user since you won't have anything.

**Comment by nanderson815** [comment]
` // Some props take time to get ready so return null when uid not avaialble
        if (this.props.user.uid === null || this.props.user.teamUid === null) {
         return null;
         }`


The code above is the culprit (Line 180, Dashtest.js). The teamUid is deleted when selecting a team, which causes the dash to render rnull.

**Comment by plinck** [comment]
Even getting rid of team makes dashboard show blanks for all items - even *my* activities and total activities so that still Neds to Abe fixed.  If user isn't on team, the team stuff should be blank or say something like no team activity or user isn't on a team, but should not just be blank
