### ISSUE TITLE
Add user URL to context

### ISSUE THREAD

**Issue by nanderson815** [plinck/TeamATC#317]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by plinck** [comment]
Easier than I thought so I knocked it out before heading out to hang on my porch.

NOTE: It is only for User results records and if I don't find one on the user, I give it a blank string.

**Comment by plinck** [comment]
Note: Also - it want appear until totals are recalculated for a challenge - either from activity (any activity) or force recall from admin page
